# Result Type 👀</br>

**📌 Rowan의 글을 참고해서 쓰는 TIL입니다.**</br>

**✅ Result Type은 Swift Standard Library에 구현되어있는 열거형 데이터타입 입니다.</br>`success`와 `failure` 두 가지 경우로 나뉘어 value를 저장합니다.**</br>

**✏️ Result Type의 `success`와 `failure` 타입으로 나뉘는 것은 switch 형태와 유사합니다.**

```swift!
@frozen enum Result<Success, Failure> where Failure: Error
```

공식 문서에 정의된 내용을 살펴보면 `Failure`의 경우 `Error` 프로토콜을 채택하고 있습니다.
**✅ 그로인하여 `do-catch`문과 유사하게 오류 처리가 가능하다는 특징이 있습니다.**</br>

**📜 아래의 예시를 봐봅시다**</br>

```swift!
enum LottoError: Error {
    case notMatched
    case unknownError
}

var resultArray: [Result<String, Error>] = []

func lottoMachine(inputNumbers: [Int]) throws -> String {
    var lottoNumber = Int.random(in: 1...10)
    for _ in inputNumbers {
        if inputNumbers.contains(lottoNumber) {
            return "당첨"
        } else {
            throw LottoError.notMatched
        }
    }
    throw LottoError.unknownError
}

for _ in 1...10 {
    let lottery = Result { try lottoMachine(inputNumbers: [1,2,3,4,5]) }
    resultArray.append(lottery)
}

for count in 0...9 {
    switch resultArray[count] {
    case .success(let matched):
        print(matched)
    case .failure(let notMatched):
        print(notMatched)
    }
}
```

1. LottoError : 오류 열거형
2. resultArray : Result 타입을 element로 갖는 빈 Array를 할당
3. lottoMachine(inputNumbers:) : 오류를 던저주는 함수 작성</br>-> 원하는 숫자를 넣은 뒤 1~10 사이의 숫자를 뽑아 넣은 숫자와 1개라도 맞을 경우 "당첨"을 return / 한개의 숫자도 안맞을 경우 throw
4. 반복문을 통해 resultArray에 try lottoMachine(inputNumbers:)의 결과를 append</br>-> return "당첨"일 경우 lottery는 matched에 "당첨"을 저장.</br>-> throw LottoError.notMatched의 경우 lottery는 notMatched에 해당 오류 저장</br>->이후 lottery에 Array elemenet로 할당됨
5. resultArray의 element 각각에 접근하여 switch-case 구문으로 해당 element 값을 출력.

## 참고 문서 📚
- [Result](https://developer.apple.com/documentation/swift/result)
- [Preserving the Results of a Throwing Expression](https://developer.apple.com/documentation/swift/preserving-the-results-of-a-throwing-expression)
- [Rowan's post](https://hackmd.io/mwQFmmVARqWk377XdETWRQ)
